### ISSUE TITLE
Python time limits make error when package is updated

### ISSUE THREAD

**Issue by OlimpijskieKoloInformatyczne** [sio2project/oioioi#215]
Problem:
In case of special limits for Python in config.yml, the second upload of task package fails.

Description:
In case file config.yml consists the below entry
-------
override_limits:
  py:
    time_limit: 22000
-------
the package can be uploaded only once.
The second upload of the package (update) - fails.

Importance:
As the Python is top 1 programming language this is huge critical issue.

For more details:
kontakt@oki.org.pl
Daniel Olkowski

**Comment by A-dead-pixel** [comment]
Traceback and stuff from a failed package reupload:
```
Failed operation: _prepare_overrides
Operation description: Prepares overrides for specified language, initially setting to default limits.
 
Error description: IntegrityError('duplicate key value violates unique constraint "programs_languageoverridefortest_test_id_language_883bb4c6_uniq"\nDETAIL:  Key (test_id, language)=(1, cpp) already exists.\n')
 
Traceback (most recent call last):
  File "/home/oioioi/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "programs_languageoverridefortest_test_id_language_883bb4c6_uniq"
DETAIL:  Key (test_id, language)=(1, cpp) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/sio2/oioioi/oioioi/problems/models.py", line 452, in manager
    yield None
  File "/sio2/oioioi/oioioi/problems/unpackmgr.py", line 40, in unpackmgr_job
    env = backend.unpack(env)
  File "/sio2/oioioi/oioioi/sinolpack/package.py", line 1421, in unpack
    ).unpack(env, package)
  File "/sio2/oioioi/oioioi/sinolpack/package.py", line 336, in unpack
    return self._extract_and_process_package()
  File "/sio2/oioioi/oioioi/sinolpack/package.py", line 389, in _extract_and_process_package
    self._process_package()
  File "/sio2/oioioi/oioioi/sinolpack/package.py", line 432, in _process_package
    self._generate_tests()
  File "/sio2/oioioi/oioioi/sinolpack/package.py", line 407, in wrapper
    six.reraise(PackageProcessingError, error, sys.exc_info()[2])
  File "/home/oioioi/.local/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/sio2/oioioi/oioioi/sinolpack/package.py", line 401, in wrapper
    return func(*args, **kwargs)
  File "/sio2/oioioi/oioioi/sinolpack/package.py", line 718, in _generate_tests
    self._process_language_override()
  File "/sio2/oioioi/oioioi/sinolpack/package.py", line 407, in wrapper
    six.reraise(PackageProcessingError, error, sys.exc_info()[2])
  File "/home/oioioi/.local/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/sio2/oioioi/oioioi/sinolpack/package.py", line 401, in wrapper
    return func(*args, **kwargs)
  File "/sio2/oioioi/oioioi/sinolpack/package.py", line 1129, in _process_language_override
    self._prepare_overrides(lang)
  File "/sio2/oioioi/oioioi/sinolpack/package.py", line 417, in wrapper
    six.reraise(PackageProcessingError, error, sys.exc_info()[2])
  File "/home/oioioi/.local/lib/python3.7/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/sio2/oioioi/oioioi/sinolpack/package.py", line 401, in wrapper
    return func(*args, **kwargs)
  File "/sio2/oioioi/oioioi/sinolpack/package.py", line 1145, in _prepare_overrides
    language=lang,
  File "/home/oioioi/.local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/oioioi/.local/lib/python3.7/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/oioioi/.local/lib/python3.7/site-packages/django/db/models/base.py", line 740, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/oioioi/.local/lib/python3.7/site-packages/django/db/models/base.py", line 778, in save_base
    force_update, using, update_fields,
  File "/home/oioioi/.local/lib/python3.7/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/oioioi/.local/lib/python3.7/site-packages/django/db/models/base.py", line 921, in _do_insert
    using=using, raw=raw,
  File "/home/oioioi/.local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/oioioi/.local/lib/python3.7/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/oioioi/.local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/home/oioioi/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/oioioi/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/oioioi/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/oioioi/.local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/oioioi/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "programs_languageoverridefortest_test_id_language_883bb4c6_uniq"
DETAIL:  Key (test_id, language)=(1, cpp) already exists.
```
