### ISSUE TITLE
Docker install fails with TeacherAuthBackend error

### ISSUE THREAD

**Issue by m4tx** [sio2project/oioioi#27]
On the latest master (de2d573a), standard Docker install ends up with:
```
Step 32/32 : RUN ./manage.py download_sandboxes -q -y -c /sio2/sandboxes
 ---> Running in dc7664e2c385
/home/oioioi/.local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/oioioi/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/oioioi/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/oioioi/.local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/oioioi/.local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/oioioi/.local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/sio2/oioioi/oioioi/teachers/models.py", line 14, in <module>
    raise ImproperlyConfigured("When using teacher module "
django.core.exceptions.ImproperlyConfigured: When using teacher module you have to activate TeacherAuthBackend
ERROR: Service 'web' failed to build: The command '/bin/sh -c ./manage.py download_sandboxes -q -y -c /sio2/sandboxes' returned a non-zero code: 1
```

By "standard Docker install" I mean:

```sh
$ docker build -t oioioi-base -f Dockerfile.base .
$ docker-compose up
```

When trying to use commit before 5b35be9618aa348ef8a028d506e2faeaf2023e91, the same thing happens as in #26.

**Comment by cytadela8** [comment]
This issue no longer happens. Docker install works now.
