### ISSUE TITLE
Python compiler problems

### ISSUE THREAD

**Issue by jstpp** [sio2project/oioioi#272]
Hey!
I have some problems with judging user's submissions... But only in Python. I'm wondering what could I change to make it work...

```
Traceback (most recent call last):
  File "/sio2/oioioi/oioioi/evalmgr/tasks.py", line 342, in evalmgr_job
    raise RuntimeError(
RuntimeError: Error from workers:
Some tasks in a group failed.

Exception: received from workerab26f6f18c35@172.18.0.5:42372: exception: <twisted.python.failure.Failure builtins.RuntimeError: Module providing 'sio.compilers:python' not found>
Remote traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/oioioi/.local/lib/python3.8/site-packages/sio/protocol/worker.py", line 14, in _runner_wrap
    renv = runner.run(env)
  File "/home/oioioi/.local/lib/python3.8/site-packages/sio/workers/runner.py", line 75, in run
    environ = first_entry_point('sio.jobs', environ['job_type'])(environ)
  File "/home/oioioi/.local/lib/python3.8/site-packages/sio/compilers/job.py", line 13, in run
    compiler = first_entry_point('sio.compilers', environ['compiler'].split('.')[0])
  File "/home/oioioi/.local/lib/python3.8/site-packages/sio/workers/util.py", line 30, in first_entry_point
    raise RuntimeError("Module providing '%s:%s' not found" % (group, name or ''))
builtins.RuntimeError: Module providing 'sio.compilers:python' not found

TB:
Traceback (most recent call last):
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1116, in _cbDeferred
    self.callback(self.resultList)
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/internet/defer.py", line 460, in callback
    self._startRunCallbacks(result)
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/oioioi/.local/lib/python3.8/site-packages/sio/sioworkersd/taskmanager.py", line 264, in _collect
    raise MultiException("Some tasks in a group failed.", failed)
sio.sioworkersd.taskmanager.MultiException: Some tasks in a group failed.

Exception: received from workerab26f6f18c35@172.18.0.5:42372: exception: <twisted.python.failure.Failure builtins.RuntimeError: Module providing 'sio.compilers:python' not found>
Remote traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/oioioi/.local/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/oioioi/.local/lib/python3.8/site-packages/sio/protocol/worker.py", line 14, in _runner_wrap
    renv = runner.run(env)
  File "/home/oioioi/.local/lib/python3.8/site-packages/sio/workers/runner.py", line 75, in run
    environ = first_entry_point('sio.jobs', environ['job_type'])(environ)
  File "/home/oioioi/.local/lib/python3.8/site-packages/sio/compilers/job.py", line 13, in run
    compiler = first_entry_point('sio.compilers', environ['compiler'].split('.')[0])
  File "/home/oioioi/.local/lib/python3.8/site-packages/sio/workers/util.py", line 30, in first_entry_point
    raise RuntimeError("Module providing '%s:%s' not found" % (group, name or ''))
builtins.RuntimeError: Module providing 'sio.compilers:python' not found
```

I installed OIOIOI three days ago using docker.

**Comment by A-dead-pixel** [comment]
Hello, unfortunately support for Python and also 64-bit compilation/execution is currently missing from the main sioworkers repo.
https://github.com/sio2project/oioioi/issues/52 seems to include the same problem.
I *think* it probably won't be added anytime soon, though you could try to use the patches mentioned in https://github.com/sio2project/sioworkers/issues/8.
