### ISSUE TITLE
Docker for production fails to build

### ISSUE THREAD

**Issue by cierzniak** [sio2project/oioioi#42]
When Docker tries to download https://downloads.sio2project.mimuw.edu.pl/sandboxes/sio2jail_exec-sandbox-1.3.0.tar.gz server responds with 403 FORBIDDEN
```
Step 21/22 : RUN ./manage.py supervisor > /dev/null --daemonize &&     ./manage.py download_sandboxes -q -y -c /sio2/sandboxes &&     ./manage.py supervisor stop all
 ---> Running in f4b87cfe431c
--- Downloading Manifest ...

--- Looking for license ...

--- Preparing ...

--- Downloading sandboxes ...

2020-03-18 11:52:04 URL:https://downloads.sio2project.mimuw.edu.pl/sandboxes/compiler-fpc.2_4_2.tar.gz [9888106/9888106] -> "compiler-fpc.2_4_2.tar.gz" [1]
2020-03-18 11:52:06 URL:https://downloads.sio2project.mimuw.edu.pl/sandboxes/compiler-fpc.2_4_4.tar.gz [8765962/8765962] -> "compiler-fpc.2_4_4.tar.gz" [1]
2020-03-18 11:52:09 URL:https://downloads.sio2project.mimuw.edu.pl/sandboxes/compiler-fpc.2_6_2.tar.gz [14271786/14271786] -> "compiler-fpc.2_6_2.tar.gz" [1]
2020-03-18 11:52:13 URL:https://downloads.sio2project.mimuw.edu.pl/sandboxes/compiler-gcc.4_6_3.tar.gz [28823240/28823240] -> "compiler-gcc.4_6_3.tar.gz" [1]
2020-03-18 11:52:19 URL:https://downloads.sio2project.mimuw.edu.pl/sandboxes/compiler-gcc.4_8_2.tar.gz [35360033/35360033] -> "compiler-gcc.4_8_2.tar.gz" [1]
2020-03-18 11:52:29 URL:https://downloads.sio2project.mimuw.edu.pl/sandboxes/compiler-gcc.6_3_0.tar.gz [58392873/58392873] -> "compiler-gcc.6_3_0.tar.gz" [1]
2020-03-18 11:52:41 URL:https://downloads.sio2project.mimuw.edu.pl/sandboxes/compiler-gcc.8_3_0-amd64.tar.gz [71363422/71363422] -> "compiler-gcc.8_3_0-amd64.tar.gz" [1]
2020-03-18 11:52:53 URL:https://downloads.sio2project.mimuw.edu.pl/sandboxes/compiler-gcc.8_3_0-i386.tar.gz [70202073/70202073] -> "compiler-gcc.8_3_0-i386.tar.gz" [1]
2020-03-18 11:53:25 URL:https://downloads.sio2project.mimuw.edu.pl/sandboxes/compiler-java.1_8.tar.gz [174984266/174984266] -> "compiler-java.1_8.tar.gz" [1]
2020-03-18 11:53:25 URL:https://downloads.sio2project.mimuw.edu.pl/sandboxes/exec-sandbox.tar.gz [552573/552573] -> "exec-sandbox.tar.gz" [1]
2020-03-18 11:53:32 URL:https://downloads.sio2project.mimuw.edu.pl/sandboxes/vcpu_exec-sandbox.tar.gz [35880132/35880132] -> "vcpu_exec-sandbox.tar.gz" [1]
2020-03-18 11:53:32 URL:https://downloads.sio2project.mimuw.edu.pl/sandboxes/proot-sandbox.tar.gz [2004185/2004185] -> "proot-sandbox.tar.gz" [1]
2020-03-18 11:53:32 URL:https://downloads.sio2project.mimuw.edu.pl/sandboxes/null-sandbox.tar.gz [10240/10240] -> "null-sandbox.tar.gz" [1]
2020-03-18 11:53:33 URL:https://downloads.sio2project.mimuw.edu.pl/sandboxes/sio2jail_exec-sandbox.tar.gz [1293214/1293214] -> "sio2jail_exec-sandbox.tar.gz" [1]
2020-03-18 11:53:34 URL:https://downloads.sio2project.mimuw.edu.pl/sandboxes/sio2jail_exec-sandbox-1.1.0.tar.gz [6803001/6803001] -> "sio2jail_exec-sandbox-1.1.0.tar.gz" [1]
https://downloads.sio2project.mimuw.edu.pl/sandboxes/sio2jail_exec-sandbox-1.3.0.tar.gz:
2020-03-18 11:53:34 ERROR 403: Forbidden.
FINISHED --2020-03-18 11:53:34--
Total wall clock time: 1m 34s
Downloaded: 15 files, 495M in 1m 30s (5.48 MB/s)
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/oioioi/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/oioioi/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/oioioi/.local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/oioioi/.local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/sio2/oioioi/oioioi/sioworkers/management/commands/download_sandboxes.py", line 125, in handle
    cwd=download_dir)
  File "/sio2/oioioi/oioioi/base/utils/execute.py", line 83, in execute
    (command, stdout))
oioioi.base.utils.execute.ExecuteError: Failed to execute command: wget -N -i - -nv
None
```
Is there any problem with this package or just server issue?

**Comment by Wolf480pl** [comment]
Server issue. Should be fixed now.
