### ISSUE TITLE
Cannot build OIOIOI container

### ISSUE THREAD

**Issue by KarolAntczak** [sio2project/oioioi#46]
Hi,

After executing `docker build .` it proceeds up to sandboxes saving phase. Then, I've got the following error:

```
--- Saving sandboxes to the Filetracker ...



compiler-fpc.2_4_2.tar.gz

Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/oioioi/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/oioioi/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/oioioi/.local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/oioioi/.local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/sio2/oioioi/oioioi/sioworkers/management/commands/download_sandboxes.py", line 171, in handle
    filetracker.put_file('/sandboxes/' + basename, local_file)
  File "/home/oioioi/.local/lib/python2.7/site-packages/filetracker/client/client.py", line 287, in put_file
    name, filename, compress_hint=compress_hint)
  File "/home/oioioi/.local/lib/python2.7/site-packages/filetracker/client/remote_data_store.py", line 79, in wrapped
    ret = fn(*args, **kwargs)
  File "/home/oioioi/.local/lib/python2.7/site-packages/filetracker/client/remote_data_store.py", line 63, in wrapped
    raise FiletrackerError('Error making HTTP request: %s' % e)
filetracker.client.FiletrackerError: Error making HTTP request: HTTPConnectionPool(host='web', port=9999): Max retries exceeded with url: /version/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd6ee59fa90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Exception AttributeError: "'NoneType' object has no attribute 'close'" in <bound method FcntlLockManager.__del__ of <filetracker.client.lock_manager.FcntlLockManager object at 0x7fd6ee646b50>> ignored
The command '/bin/sh -c ./manage.py supervisor > /dev/null --daemonize --nolaunch=uwsgi &&     ./manage.py download_sandboxes -q -y -c /sio2/sandboxes &&     ./manage.py supervisor stop all' returned a non-zero code: 1
```
 
Any help would be appreciated.

**Comment by A-dead-pixel** [comment]
You need to add ``--add-host web:127.0.0.1`` to the ``docker build`` command.
I think the whole command should be in the Readme, as the only mentioned command for building the docker image is ``OIOIOI_UID=$(id -u) docker-compose -f docker-compose-dev.yml -f extra/docker/docker-compose-dev-noserver.yml build``, which looks specific to the "Docker (for development)" use case (and if someone wants to build the image for deployment, they won't look in that section immediately).

**Comment by Iteron-dev** [comment]
As has been mentioned for a long time, there is `easy-toolbox.py` and the `Dockerfile`&`docker-compose.yml` have been refactored multiple times, including a change in how sandboxes are fetched.
Closing.
