### ISSUE TITLE
supervisor error

### ISSUE THREAD

**Issue by InfoX1337** [sio2project/oioioi#48]
While setting up a new install, i get this error
`(venv) administrator@testserver2:~/oioioi/sio2/deployment$ ./manage.py supervisor
/home/administrator/oioioi/sio2/oioioi/oioioi/base/captcha_check.py:42: CaptchaAudioWarning: Audio playback of captcha is turned off, because no flite executable was found in PATH, and CAPTCHA_FLITE_PATH was not set to any path
  warnings.warn(
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'contest:oioioiadmin' isn't unique. You may not be able to reverse all URLs in this namespace
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/administrator/oioioi/sio2/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/administrator/oioioi/sio2/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/administrator/oioioi/sio2/venv/lib/python3.8/site-packages/djsupervisor/management/commands/supervisor.py", line 179, in run_from_argv
    return super(Command,self).run_from_argv(argv)
  File "/home/administrator/oioioi/sio2/venv/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/administrator/oioioi/sio2/venv/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/administrator/oioioi/sio2/venv/lib/python3.8/site-packages/djsupervisor/management/commands/supervisor.py", line 192, in handle
    return supervisord.main(("-c",cfg_file))
  File "/home/administrator/oioioi/sio2/venv/lib/python3.8/site-packages/supervisor/supervisord.py", line 352, in main
    options.realize(args, doc=__doc__)
  File "/home/administrator/oioioi/sio2/venv/lib/python3.8/site-packages/supervisor/options.py", line 485, in realize
    Options.realize(self, *arg, **kw)
  File "/home/administrator/oioioi/sio2/venv/lib/python3.8/site-packages/supervisor/options.py", line 310, in realize
    self.process_config()
  File "/home/administrator/oioioi/sio2/venv/lib/python3.8/site-packages/supervisor/options.py", line 549, in process_config
    Options.process_config(self, do_usage=do_usage)
  File "/home/administrator/oioioi/sio2/venv/lib/python3.8/site-packages/supervisor/options.py", line 318, in process_config
    self.process_config_file(do_usage)
  File "/home/administrator/oioioi/sio2/venv/lib/python3.8/site-packages/supervisor/options.py", line 348, in process_config_file
    self.read_config(self.configfile)
  File "/home/administrator/oioioi/sio2/venv/lib/python3.8/site-packages/supervisor/options.py", line 576, in read_config
    parser.read_file(fp)
  File "/usr/lib/python3.8/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.8/configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
TypeError: 'OnDemandStringIO' object is not iterable
(venv) administrator@testserver2:~/oioioi/sio2/deployment$`
Any idea why this doesnt work?

**Comment by Michcioperz** [comment]
Hi, which installation method did you use? Assuming you did the manual install, which requirements.txt did you use? This is just my intuition, but type errors with things like StringIO scream "python 2/3 mismatch" to me. And I just looked at install docs, and uhh, I don't think I'm going to blame you if it turns out to be that

**Comment by InfoX1337** [comment]
Hi,
i have followed the INSTALL.rst file (https://github.com/sio2project/oioioi/blob/master/INSTALL.rst) 
The issues arrived when i tried to launch supervisor (`./manage.py supervisor`)

**Comment by InfoX1337** [comment]
I also have a question, where can i find the auto install archive? since i couldnt find it anywhere

**Comment by DietPawel** [comment]
Just an idea: Did you used [requirements_py3.txt](https://github.com/sio2project/oioioi/blob/master/requirements_py3.txt) as you are using Python 3.8?

**Comment by Michcioperz** [comment]
> Just an idea: Did you used [requirements_py3.txt](https://github.com/sio2project/oioioi/blob/master/requirements_py3.txt) as you are using Python 3.8?

This is pretty much what I was hinting at last night. Since they say they followed the INSTALL file, I'm assuming they used the unsuffixed one. So the supervisor version is probably messed up.

**Comment by InfoX1337** [comment]
so i havent used requirements_py3.txt I will try to reinstall the whole project, thanks for the help so far! will update yall soon

**Comment by InfoX1337** [comment]
now after reinstalling everything, i get theese errors?
`
(venv) oioioi@testserver2:~/sio2/deployment$ ./manage.py supervisor
/home/oioioi/sio2/oioioi/oioioi/base/captcha_check.py:42: CaptchaAudioWarning: Audio playback of captcha is turned off, because no flite executable was found in PATH, and CAPTCHA_FLITE_PATH was not set to any path
  warnings.warn(
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'contest:oioioiadmin' isn't unique. You may not be able to reverse all URLs in this namespace
2021-11-13 17:45:35,039 WARN For [program:django-http], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
2021-11-13 17:45:35,039 INFO Set uid to user 1001 succeeded
2021-11-13 17:45:35,042 INFO RPC interface 'supervisor' initialized
2021-11-13 17:45:35,042 INFO supervisord started with pid 29189
2021-11-13 17:45:36,046 INFO spawned: 'django-http' with pid 29192
2021-11-13 17:45:36,050 INFO spawned: 'evalmgr' with pid 29193
2021-11-13 17:45:36,053 INFO spawned: 'filetracker-server' with pid 29194
2021-11-13 17:45:36,057 INFO spawned: 'mailnotifyd' with pid 29195
2021-11-13 17:45:36,059 INFO spawned: 'oioioiworker' with pid 29196
2021-11-13 17:45:36,063 INFO spawned: 'rankingsd' with pid 29197
2021-11-13 17:45:36,066 INFO spawned: 'receive_from_workers' with pid 29198
2021-11-13 17:45:36,069 INFO spawned: 'sioworkersd' with pid 29199
2021-11-13 17:45:36,073 INFO spawned: 'unpackmgr' with pid 29200
2021-11-13 17:45:36,092 DEBG 'sioworkersd' stderr output:
python2: can't open file '/home/oioioi/.local/bin//twistd': [Errno 2] No such file or directory

2021-11-13 17:45:36,093 DEBG fd 43 closed, stopped monitoring <POutputDispatcher at 140312403667120 for <Subprocess at 140312404120672 with name sioworkersd in state STARTING> (stderr)>
2021-11-13 17:45:36,093 DEBG fd 39 closed, stopped monitoring <POutputDispatcher at 140312404120720 for <Subprocess at 140312404120672 with name sioworkersd in state STARTING> (stdout)>
2021-11-13 17:45:36,316 DEBG 'django-http' stdout output:
Traceback (most recent call last):
  File "/home/oioioi/sio2/deployment//manage.py", line 11, in <module>
    from oioioi.deployment.init import init_env
ModuleNotFoundError: No module named 'oioioi'

2021-11-13 17:45:36,316 INFO exited: sioworkersd (exit status 2; not expected)
2021-11-13 17:45:36,316 DEBG received SIGCHLD indicating a child quit
2021-11-13 17:45:36,325 DEBG 'mailnotifyd' stderr output:
Traceback (most recent call last):
  File "/home/oioioi/sio2/deployment/manage.py", line 11, in <module>
    from oioioi.deployment.init import init_env
ModuleNotFoundError: No module named 'oioioi'

2021-11-13 17:45:36,326 INFO gave up: sioworkersd entered FATAL state, too many start retries too quickly
2021-11-13 17:45:36,337 DEBG 'receive_from_workers' stderr output:
Traceback (most recent call last):
  File "/home/oioioi/sio2/deployment/manage.py", line 11, in <module>
    from oioioi.deployment.init import init_env
ModuleNotFoundError: No module named 'oioioi'

2021-11-13 17:45:36,343 DEBG 'rankingsd' stderr output:
Traceback (most recent call last):
  File "/home/oioioi/sio2/deployment/manage.py", line 11, in <module>
    from oioioi.deployment.init import init_env
ModuleNotFoundError: No module named 'oioioi'

2021-11-13 17:45:36,356 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 140312403582880 for <Subprocess at 140312403986224 with name django-http in state STARTING> (stdout)>
2021-11-13 17:45:36,367 DEBG fd 19 closed, stopped monitoring <POutputDispatcher at 140312404119952 for <Subprocess at 140312404119904 with name mailnotifyd in state STARTING> (stdout)>
2021-11-13 17:45:36,367 DEBG fd 23 closed, stopped monitoring <POutputDispatcher at 140312403666448 for <Subprocess at 140312404119904 with name mailnotifyd in state STARTING> (stderr)>
2021-11-13 17:45:36,367 INFO exited: django-http (exit status 1; not expected)
2021-11-13 17:45:36,367 INFO exited: mailnotifyd (exit status 1; not expected)
2021-11-13 17:45:36,367 DEBG received SIGCHLD indicating a child quit
2021-11-13 17:45:36,377 DEBG fd 29 closed, stopped monitoring <POutputDispatcher at 140312404120336 for <Subprocess at 140312404120288 with name rankingsd in state STARTING> (stdout)>
2021-11-13 17:45:36,377 DEBG fd 33 closed, stopped monitoring <POutputDispatcher at 140312403667312 for <Subprocess at 140312404120288 with name rankingsd in state STARTING> (stderr)>
2021-11-13 17:45:36,377 INFO gave up: mailnotifyd entered FATAL state, too many start retries too quickly
2021-11-13 17:45:36,377 INFO exited: rankingsd (exit status 1; not expected)
2021-11-13 17:45:36,377 DEBG fd 34 closed, stopped monitoring <POutputDispatcher at 140312404120528 for <Subprocess at 140312404120480 with name receive_from_workers in state STARTING> (stdout)>
2021-11-13 17:45:36,377 DEBG fd 38 closed, stopped monitoring <POutputDispatcher at 140312403667744 for <Subprocess at 140312404120480 with name receive_from_workers in state STARTING> (stderr)>
2021-11-13 17:45:36,377 INFO exited: receive_from_workers (exit status 1; not expected)
2021-11-13 17:45:36,377 DEBG received SIGCHLD indicating a child quit
2021-11-13 17:45:36,378 INFO gave up: rankingsd entered FATAL state, too many start retries too quickly
2021-11-13 17:45:36,378 INFO gave up: receive_from_workers entered FATAL state, too many start retries too quickly
2021-11-13 17:45:36,456 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:36 INFO     (29202) gunicorn.error  Starting gunicorn 19.9.0

2021-11-13 17:45:36,457 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:36 INFO     (29202) gunicorn.error  Listening at: http://127.0.0.1:9999 (29202)

2021-11-13 17:45:36,457 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:36 INFO     (29202) gunicorn.error  Using worker: gevent

2021-11-13 17:45:36,459 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:36 INFO     (29206) gunicorn.error  Booting worker with pid: 29206

2021-11-13 17:45:36,491 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:36 INFO     (29207) gunicorn.error  Booting worker with pid: 29207

2021-11-13 17:45:36,550 DEBG 'oioioiworker' stdout output:
2021-11-13T17:45:36+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 20.3.0 (/home/oioioi/sio2/venv/bin/python 3.8.10) starting up.

2021-11-13 17:45:36,550 DEBG 'oioioiworker' stdout output:
2021-11-13T17:45:36+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
2021-11-13T17:45:36+0000 [sio.protocol.worker.WorkerFactory#info] Starting factory <sio.protocol.worker.WorkerFactory object at 0x7f5ecfcbdc10>

2021-11-13 17:45:36,554 DEBG 'oioioiworker' stdout output:
2021-11-13T17:45:36+0000 [Uninitialized] <twisted.internet.tcp.Connector instance at 0x7f5ecfc48040 disconnected IPv4Address(type='TCP', host='localhost', port=7888)> will retry in 2 seconds

2021-11-13 17:45:36,554 DEBG 'oioioiworker' stdout output:
2021-11-13T17:45:36+0000 [sio.protocol.worker.WorkerFactory#info] Stopping factory <sio.protocol.worker.WorkerFactory object at 0x7f5ecfcbdc10>

2021-11-13 17:45:36,573 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:36 INFO     (29209) gunicorn.error  Booting worker with pid: 29209

2021-11-13 17:45:36,641 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:36 INFO     (29210) gunicorn.error  Booting worker with pid: 29210

2021-11-13 17:45:36,685 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:36 INFO     (29211) gunicorn.error  Booting worker with pid: 29211

2021-11-13 17:45:36,719 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:36 INFO     (29212) gunicorn.error  Booting worker with pid: 29212

2021-11-13 17:45:36,818 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:36 INFO     (29213) gunicorn.error  Booting worker with pid: 29213

2021-11-13 17:45:36,878 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:36 INFO     (29214) gunicorn.error  Booting worker with pid: 29214

2021-11-13 17:45:36,907 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:36 INFO     (29215) gunicorn.error  Booting worker with pid: 29215

2021-11-13 17:45:36,999 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:36 INFO     (29217) gunicorn.error  Booting worker with pid: 29217

2021-11-13 17:45:37,061 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:37 INFO     (29218) gunicorn.error  Booting worker with pid: 29218

2021-11-13 17:45:37,061 INFO success: evalmgr entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-11-13 17:45:37,061 INFO success: filetracker-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-11-13 17:45:37,061 INFO success: oioioiworker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-11-13 17:45:37,132 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:37 INFO     (29219) gunicorn.error  Booting worker with pid: 29219

2021-11-13 17:45:37,132 INFO success: unpackmgr entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-11-13 17:45:37,196 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:37 INFO     (29220) gunicorn.error  Booting worker with pid: 29220

2021-11-13 17:45:37,209 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:37 INFO     (29221) gunicorn.error  Booting worker with pid: 29221

2021-11-13 17:45:37,286 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:37 INFO     (29222) gunicorn.error  Booting worker with pid: 29222

2021-11-13 17:45:37,328 DEBG 'filetracker-server' stdout output:
2021-11-13 17:45:37 INFO     (29223) gunicorn.error  Booting worker with pid: 29223

2021-11-13 17:45:37,500 DEBG 'evalmgr' stderr output:
/home/oioioi/sio2/oioioi/oioioi/base/captcha_check.py:42: CaptchaAudioWarning: Audio playback of captcha is turned off, because no flite executable was found in PATH, and CAPTCHA_FLITE_PATH was not set to any path
  warnings.warn(
/home/oioioi/sio2/venv/lib/python3.8/site-packages/celery/backends/amqp.py:65: CPendingDeprecationWarning:
    The AMQP result backend is scheduled for deprecation in     version 4.0 and removal in version v5.0.     Please use RPC backend or a persistent backend.

  deprecated.warn(
[2021-11-13 17:45:37,500: INFO/MainProcess] Connected to sqla+sqlite:////tmp/celerydb.sqlite

2021-11-13 17:45:37,503 INFO spawned: 'django-http' with pid 29234
2021-11-13 17:45:37,524 DEBG 'evalmgr' stderr output:
[2021-11-13 17:45:37,524: WARNING/MainProcess] /home/oioioi/sio2/venv/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

2021-11-13 17:45:37,524 DEBG 'evalmgr' stderr output:
[2021-11-13 17:45:37,524: INFO/MainProcess] celery@testserver2 ready.

2021-11-13 17:45:37,525 DEBG 'unpackmgr' stderr output:
/home/oioioi/sio2/oioioi/oioioi/base/captcha_check.py:42: CaptchaAudioWarning: Audio playback of captcha is turned off, because no flite executable was found in PATH, and CAPTCHA_FLITE_PATH was not set to any path
  warnings.warn(
/home/oioioi/sio2/venv/lib/python3.8/site-packages/celery/backends/amqp.py:65: CPendingDeprecationWarning:
    The AMQP result backend is scheduled for deprecation in     version 4.0 and removal in version v5.0.     Please use RPC backend or a persistent backend.

  deprecated.warn(
[2021-11-13 17:45:37,524: INFO/MainProcess] Connected to sqla+sqlite:////tmp/celerydb.sqlite

2021-11-13 17:45:37,548 DEBG 'unpackmgr' stderr output:
[2021-11-13 17:45:37,548: WARNING/MainProcess] /home/oioioi/sio2/venv/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

2021-11-13 17:45:37,549 DEBG 'unpackmgr' stderr output:
[2021-11-13 17:45:37,548: INFO/MainProcess] celery@testserver2 ready.

2021-11-13 17:45:37,656 DEBG 'django-http' stdout output:
Traceback (most recent call last):
  File "/home/oioioi/sio2/deployment//manage.py", line 11, in <module>
    from oioioi.deployment.init import init_env
ModuleNotFoundError: No module named 'oioioi'

2021-11-13 17:45:37,672 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 140312403986176 for <Subprocess at 140312403986224 with name django-http in state STARTING> (stdout)>
2021-11-13 17:45:37,673 INFO exited: django-http (exit status 1; not expected)
2021-11-13 17:45:37,673 DEBG received SIGCHLD indicating a child quit
2021-11-13 17:45:39,275 DEBG 'oioioiworker' stdout output:
2021-11-13T17:45:39+0000 [sio.protocol.worker.WorkerFactory#info] Starting factory <sio.protocol.worker.WorkerFactory object at 0x7f5ecfcbdc10>

2021-11-13 17:45:39,277 DEBG 'oioioiworker' stdout output:
2021-11-13T17:45:39+0000 [Uninitialized] <twisted.internet.tcp.Connector instance at 0x7f5ecfc48040 disconnected IPv4Address(type='TCP', host='localhost', port=7888)> will retry in 8 seconds

2021-11-13 17:45:39,277 DEBG 'oioioiworker' stdout output:
2021-11-13T17:45:39+0000 [sio.protocol.worker.WorkerFactory#info] Stopping factory <sio.protocol.worker.WorkerFactory object at 0x7f5ecfcbdc10>

2021-11-13 17:45:40,281 INFO spawned: 'django-http' with pid 29235
2021-11-13 17:45:40,439 DEBG 'django-http' stdout output:
Traceback (most recent call last):
  File "/home/oioioi/sio2/deployment//manage.py", line 11, in <module>
    from oioioi.deployment.init import init_env
ModuleNotFoundError: No module named 'oioioi'

2021-11-13 17:45:40,455 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 140312403582496 for <Subprocess at 140312403986224 with name django-http in state STARTING> (stdout)>
2021-11-13 17:45:40,455 INFO exited: django-http (exit status 1; not expected)
2021-11-13 17:45:40,455 DEBG received SIGCHLD indicating a child quit
2021-11-13 17:45:43,462 INFO spawned: 'django-http' with pid 29236
2021-11-13 17:45:43,621 DEBG 'django-http' stdout output:
Traceback (most recent call last):
  File "/home/oioioi/sio2/deployment//manage.py", line 11, in <module>
    from oioioi.deployment.init import init_env
ModuleNotFoundError: No module named 'oioioi'

2021-11-13 17:45:43,637 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 140312403986176 for <Subprocess at 140312403986224 with name django-http in state STARTING> (stdout)>
2021-11-13 17:45:43,638 INFO exited: django-http (exit status 1; not expected)
2021-11-13 17:45:43,638 DEBG received SIGCHLD indicating a child quit
2021-11-13 17:45:44,639 INFO gave up: django-http entered FATAL state, too many start retries too quickly
2021-11-13 17:45:47,863 DEBG 'oioioiworker' stdout output:
2021-11-13T17:45:47+0000 [sio.protocol.worker.WorkerFactory#info] Starting factory <sio.protocol.worker.WorkerFactory object at 0x7f5ecfcbdc10>

2021-11-13 17:45:47,864 DEBG 'oioioiworker' stdout output:
2021-11-13T17:45:47+0000 [Uninitialized] <twisted.internet.tcp.Connector instance at 0x7f5ecfc48040 disconnected IPv4Address(type='TCP', host='localhost', port=7888)> will retry in 20 seconds

2021-11-13 17:45:47,864 DEBG 'oioioiworker' stdout output:
2021-11-13T17:45:47+0000 [sio.protocol.worker.WorkerFactory#info] Stopping factory <sio.protocol.worker.WorkerFactory object at 0x7f5ecfcbdc10>

2021-11-13 17:46:08,231 DEBG 'oioioiworker' stdout output:
2021-11-13T17:46:08+0000 [sio.protocol.worker.WorkerFactory#info] Starting factory <sio.protocol.worker.WorkerFactory object at 0x7f5ecfcbdc10>

2021-11-13 17:46:08,233 DEBG 'oioioiworker' stdout output:
2021-11-13T17:46:08+0000 [Uninitialized] <twisted.internet.tcp.Connector instance at 0x7f5ecfc48040 disconnected IPv4Address(type='TCP', host='localhost', port=7888)> will retry in 45 seconds

2021-11-13 17:46:08,233 DEBG 'oioioiworker' stdout output:
2021-11-13T17:46:08+0000 [sio.protocol.worker.WorkerFactory#info] Stopping factory <sio.protocol.worker.WorkerFactory object at 0x7f5ecfcbdc10>
`
Any clue why it doesnt work now?

**Comment by DietPawel** [comment]
Is the `oioioi` module installed? Was it build with `requirements_py3.txt`, wasn't it?

**Comment by InfoX1337** [comment]
i have only installed requirements_py3.txt, didnt install the oioioi module separately

**Comment by DietPawel** [comment]
What I meant, was that there is `.` entry in requirements_py3.txt which builds oioioi package. Was the build successful? Does it list `oioioi` in the list of installed packages?

I might try the instructions on my own when I find some time, but no promises.

P.S. Have You considered using the docker image for oioioi, it probably is more up-to-date and depending on your needs it might be fine.

**Comment by InfoX1337** [comment]
yes, look at this:
```
(venv) oioioi@testserver2:~/sio2/deployment$ pip show oioioi
Name: oioioi
Version: 0.2.0.dev0
Summary: The web frontend of the SIO2 Project contesting system
Home-page: http://sio2project.mimuw.edu.pl
Author: The SIO2 Team
Author-email: sio2@sio2project.mimuw.edu.pl
License: UNKNOWN
Location: /home/oioioi/sio2/oioioi
Requires: sentry-sdk, Django, pytz, sqlalchemy, beautifulsoup4, PyYAML, python-dateutil, django-two-factor-auth, django-formtools, django-registration-redux, Celery, coreapi, dj-pagination, django-compressor, pygments, django-libsass, django-debug-toolbar, django-extensions, djangorestframework, werkzeug, pytest, pytest-django, pytest-html, pytest-xdist, pytest-cov, requests, fpdf, unicodecsv, shortuuid, dnslib, bleach, chardet, django-gravatar2, django-mptt, mistune, pika, raven, unidecode, django-nested-admin, filetracker, django-simple-captcha, phonenumbers, pdfminer.six
Required-by:
(venv) oioioi@testserver2:~/sio2/deployment$ ./manage.py supervisor
/home/oioioi/sio2/oioioi/oioioi/base/captcha_check.py:42: CaptchaAudioWarning: Audio playback of captcha is turned off, because no flite executable was found in PATH, and CAPTCHA_FLITE_PATH was not set to any path
  warnings.warn(
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'contest:oioioiadmin' isn't unique. You may not be able to reverse all URLs in this namespace
2021-11-14 11:54:17,520 WARN For [program:django-http], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
2021-11-14 11:54:17,520 INFO Set uid to user 1001 succeeded
2021-11-14 11:54:17,522 INFO RPC interface 'supervisor' initialized
2021-11-14 11:54:17,523 INFO supervisord started with pid 3462
2021-11-14 11:54:18,526 INFO spawned: 'django-http' with pid 3464
2021-11-14 11:54:18,530 INFO spawned: 'evalmgr' with pid 3465
2021-11-14 11:54:18,534 INFO spawned: 'filetracker-server' with pid 3466
2021-11-14 11:54:18,537 INFO spawned: 'mailnotifyd' with pid 3467
2021-11-14 11:54:18,540 INFO spawned: 'oioioiworker' with pid 3468
2021-11-14 11:54:18,543 INFO spawned: 'rankingsd' with pid 3469
2021-11-14 11:54:18,546 INFO spawned: 'receive_from_workers' with pid 3470
2021-11-14 11:54:18,549 INFO spawned: 'sioworkersd' with pid 3471
2021-11-14 11:54:18,552 INFO spawned: 'unpackmgr' with pid 3472
2021-11-14 11:54:18,583 DEBG 'sioworkersd' stderr output:
python2: can't open file '/home/oioioi/.local/bin//twistd': [Errno 2] No such file or directory

2021-11-14 11:54:18,583 DEBG fd 39 closed, stopped monitoring <POutputDispatcher at 140261699834976 for <Subprocess at 140261699834928 with name sioworkersd in state STARTING> (stdout)>
2021-11-14 11:54:18,583 DEBG fd 43 closed, stopped monitoring <POutputDispatcher at 140261699381376 for <Subprocess at 140261699834928 with name sioworkersd in state STARTING> (stderr)>
2021-11-14 11:54:18,583 INFO exited: sioworkersd (exit status 2; not expected)
2021-11-14 11:54:18,584 DEBG received SIGCHLD indicating a child quit
2021-11-14 11:54:18,584 INFO gave up: sioworkersd entered FATAL state, too many start retries too quickly
2021-11-14 11:54:18,800 DEBG 'django-http' stdout output:
Traceback (most recent call last):
  File "/home/oioioi/sio2/deployment//manage.py", line 11, in <module>
    from oioioi.deployment.init import init_env
ModuleNotFoundError: No module named 'oioioi'

2021-11-14 11:54:18,807 DEBG 'mailnotifyd' stderr output:
Traceback (most recent call last):
  File "/home/oioioi/sio2/deployment/manage.py", line 11, in <module>
    from oioioi.deployment.init import init_env
ModuleNotFoundError: No module named 'oioioi'
```
still says that there is no module named oioioi?

**Comment by InfoX1337** [comment]
Hold on, i have added the oioioi directory to pythonpath, and that error isnt apparent now

**Comment by InfoX1337** [comment]
now the only issue that i see is this: bootlooping oioioi worker

```
2021-11-14 12:02:52,060 DEBG 'oioioiworker' stdout output:
2021-11-14T12:02:52+0000 [sio.protocol.worker.WorkerFactory#info] Stopping factory <sio.protocol.worker.WorkerFactory object at 0x7f807edc5b80>

2021-11-14 12:03:58,213 DEBG 'oioioiworker' stdout output:
2021-11-14T12:03:58+0000 [sio.protocol.worker.WorkerFactory#info] Starting factory <sio.protocol.worker.WorkerFactory object at 0x7f807edc5b80>

2021-11-14 12:03:58,214 DEBG 'oioioiworker' stdout output:
2021-11-14T12:03:58+0000 [Uninitialized] <twisted.internet.tcp.Connector instance at 0x7f807edc5f70 disconnected IPv4Address(type='TCP', host='localhost', port=7888)> will retry in 53 seconds

2021-11-14 12:03:58,214 DEBG 'oioioiworker' stdout output:
2021-11-14T12:03:58+0000 [sio.protocol.worker.WorkerFactory#info] Stopping factory <sio.protocol.worker.WorkerFactory object at 0x7f807edc5b80>
```
Is this an firewall issue?

**Comment by torelq** [comment]
By the way, if you found a solution please show how you have fixed it, as I've got the same issue
